<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE HealthData [
<!-- HealthKit Export Version: 3 -->
<!ELEMENT HealthData (ExportDate,Me,(Record|Correlation|Workout|ActivitySummary)*)>
<!ATTLIST HealthData
  locale CDATA #REQUIRED
>
<!ELEMENT ExportDate EMPTY>
<!ATTLIST ExportDate
  value CDATA #REQUIRED
>
<!ELEMENT Me EMPTY>
<!ATTLIST Me
  HKCharacteristicTypeIdentifierDateOfBirth         CDATA #REQUIRED
  HKCharacteristicTypeIdentifierBiologicalSex       CDATA #REQUIRED
  HKCharacteristicTypeIdentifierBloodType           CDATA #REQUIRED
  HKCharacteristicTypeIdentifierFitzpatrickSkinType CDATA #REQUIRED
>
<!ELEMENT Record (MetadataEntry*)>
<!ATTLIST Record
  type          CDATA #REQUIRED
  unit          CDATA #IMPLIED
  value         CDATA #IMPLIED
  sourceName    CDATA #REQUIRED
  sourceVersion CDATA #IMPLIED
  device        CDATA #IMPLIED
  creationDate  CDATA #IMPLIED
  startDate     CDATA #REQUIRED
  endDate       CDATA #REQUIRED
>
<!-- Note: Any Records that appear as children of a correlation also appear as top-level records in this document. -->
<!ELEMENT Correlation ((MetadataEntry|Record)*)>
<!ATTLIST Correlation
  type          CDATA #REQUIRED
  sourceName    CDATA #REQUIRED
  sourceVersion CDATA #IMPLIED
  device        CDATA #IMPLIED
  creationDate  CDATA #IMPLIED
  startDate     CDATA #REQUIRED
  endDate       CDATA #REQUIRED
>
<!ELEMENT Workout ((MetadataEntry|WorkoutEvent)*)>
<!ATTLIST Workout
  workoutActivityType   CDATA #REQUIRED
  duration              CDATA #IMPLIED
  durationUnit          CDATA #IMPLIED
  totalDistance         CDATA #IMPLIED
  totalDistanceUnit     CDATA #IMPLIED
  totalEnergyBurned     CDATA #IMPLIED
  totalEnergyBurnedUnit CDATA #IMPLIED
  sourceName            CDATA #REQUIRED
  sourceVersion         CDATA #IMPLIED
  device                CDATA #IMPLIED
  creationDate          CDATA #IMPLIED
  startDate             CDATA #REQUIRED
  endDate               CDATA #REQUIRED
>
<!ELEMENT WorkoutEvent EMPTY>
<!ATTLIST WorkoutEvent
  type CDATA #REQUIRED
  date CDATA #REQUIRED
>
<!ELEMENT ActivitySummary EMPTY>
<!ATTLIST ActivitySummary
  dateComponents           CDATA #IMPLIED
  activeEnergyBurned       CDATA #IMPLIED
  activeEnergyBurnedGoal   CDATA #IMPLIED
  activeEnergyBurnedUnit   CDATA #IMPLIED
  appleExerciseTime        CDATA #IMPLIED
  appleExerciseTimeGoal    CDATA #IMPLIED
  appleStandHours          CDATA #IMPLIED
  appleStandHoursGoal      CDATA #IMPLIED
>
<!ELEMENT MetadataEntry EMPTY>
<!ATTLIST MetadataEntry
  key   CDATA #REQUIRED
  value CDATA #REQUIRED
>
]>
<HealthData locale="en_US">
 <ExportDate value="2017-11-07 10:05:13 +0200"/>
 <Me HKCharacteristicTypeIdentifierDateOfBirth="" HKCharacteristicTypeIdentifierBiologicalSex="HKBiologicalSexNotSet" HKCharacteristicTypeIdentifierBloodType="HKBloodTypeNotSet" HKCharacteristicTypeIdentifierFitzpatrickSkinType="HKFitzpatrickSkinTypeNotSet"/>
 <Record type="HKQuantityTypeIdentifierBloodGlucose" sourceName="Health" sourceVersion="10.2.1" unit="mg/dL" creationDate="2017-03-30 09:29:59 +0200" startDate="2017-03-30 09:29:00 +0200" endDate="2017-03-30 09:29:00 +0200" value="81">
  <MetadataEntry key="HKWasUserEntered" value="1"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierBloodGlucose" sourceName="Health" sourceVersion="10.3.1" unit="mg/dL" creationDate="2017-05-23 09:49:16 +0200" startDate="2017-05-23 09:49:00 +0200" endDate="2017-05-23 09:49:00 +0200" value="90">
  <MetadataEntry key="HKWasUserEntered" value="1"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierBloodGlucose" sourceName="Health" sourceVersion="10.3.1" unit="mg/dL" creationDate="2017-05-23 11:07:46 +0200" startDate="2017-05-23 11:07:00 +0200" endDate="2017-05-23 11:07:00 +0200" value="80">
  <MetadataEntry key="HKWasUserEntered" value="1"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierBloodGlucose" sourceName="Health" sourceVersion="10.3.1" unit="mg/dL" creationDate="2017-05-23 12:42:27 +0200" startDate="2017-05-23 12:42:00 +0200" endDate="2017-05-23 12:42:00 +0200" value="115">
  <MetadataEntry key="HKWasUserEntered" value="1"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierBloodGlucose" sourceName="Health" sourceVersion="10.3.1" unit="mg/dL" creationDate="2017-05-24 13:43:46 +0200" startDate="2017-05-24 13:43:00 +0200" endDate="2017-05-24 13:43:00 +0200" value="666">
  <MetadataEntry key="HKWasUserEntered" value="1"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierBloodGlucose" sourceName="mySugr" sourceVersion="1661" unit="mg/dL" creationDate="2017-05-24 14:00:05 +0200" startDate="2017-05-24 13:56:15 +0200" endDate="2017-05-24 13:56:15 +0200" value="166">
  <MetadataEntry key="HKExternalUUID" value="4F4542BB-252C-4525-B744-3D8FD424242F"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierBloodGlucose" sourceName="One Drop" sourceVersion="3.8.0.0" unit="mg/dL" creationDate="2017-05-24 14:07:09 +0200" startDate="2017-05-24 13:56:15 +0200" endDate="2017-05-24 13:56:15 +0200" value="166">
  <MetadataEntry key="App Source" value="OneDrop"/>
  <MetadataEntry key="HKWasUserEntered" value="0"/>
  <MetadataEntry key="HKExternalUUID" value="cGUtCSb2TIwLQwlHMvxQbbRv9ZiiAh9j"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierBloodGlucose" sourceName="One Drop" sourceVersion="3.8.0.0" unit="mg/dL" creationDate="2017-05-24 14:07:09 +0200" startDate="2017-05-23 09:49:00 +0200" endDate="2017-05-23 09:49:00 +0200" value="90">
  <MetadataEntry key="App Source" value="OneDrop"/>
  <MetadataEntry key="HKWasUserEntered" value="0"/>
  <MetadataEntry key="HKExternalUUID" value="75k8dkEN1ogbmbDPc7BNse4ovF5dIewc"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierBloodGlucose" sourceName="One Drop" sourceVersion="3.8.0.0" unit="mg/dL" creationDate="2017-05-24 14:07:09 +0200" startDate="2017-05-24 13:37:44 +0200" endDate="2017-05-24 13:37:44 +0200" value="98">
  <MetadataEntry key="App Source" value="OneDrop"/>
  <MetadataEntry key="HKWasUserEntered" value="0"/>
  <MetadataEntry key="HKExternalUUID" value="lwltJM2erH14SwoCR8MMHP6SoSsvON4E"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierBloodGlucose" sourceName="One Drop" sourceVersion="3.8.0.0" unit="mg/dL" creationDate="2017-05-24 14:07:09 +0200" startDate="2017-05-23 11:07:00 +0200" endDate="2017-05-23 11:07:00 +0200" value="80">
  <MetadataEntry key="App Source" value="OneDrop"/>
  <MetadataEntry key="HKWasUserEntered" value="0"/>
  <MetadataEntry key="HKExternalUUID" value="qUrF43plTnosXfg6OzMC4vIt5QsZVFFm"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierBloodGlucose" sourceName="One Drop" sourceVersion="3.8.0.0" unit="mg/dL" creationDate="2017-05-24 14:07:09 +0200" startDate="2017-05-23 12:42:00 +0200" endDate="2017-05-23 12:42:00 +0200" value="115">
  <MetadataEntry key="App Source" value="OneDrop"/>
  <MetadataEntry key="HKWasUserEntered" value="0"/>
  <MetadataEntry key="HKExternalUUID" value="3NbkZA6VbvH9qQXWYVHZOEQI2fn1nfZ0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierBloodGlucose" sourceName="One Drop" sourceVersion="3.8.0.0" unit="mg/dL" creationDate="2017-05-24 14:07:09 +0200" startDate="2017-05-24 13:43:00 +0200" endDate="2017-05-24 13:43:00 +0200" value="666">
  <MetadataEntry key="App Source" value="OneDrop"/>
  <MetadataEntry key="HKWasUserEntered" value="0"/>
  <MetadataEntry key="HKExternalUUID" value="yv0zIuHmV075DrhjtROseVHVf0MdqXus"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierBloodGlucose" sourceName="One Drop" sourceVersion="3.8.0.0" unit="mg/dL" creationDate="2017-05-24 14:07:16 +0200" startDate="2017-05-24 14:07:11 +0200" endDate="2017-05-24 14:07:11 +0200" value="58">
  <MetadataEntry key="App Source" value="OneDrop"/>
  <MetadataEntry key="HKWasUserEntered" value="1"/>
  <MetadataEntry key="HKExternalUUID" value="PfaYfThcQaCQlXFkSAH3W4SFSbGtPW3t"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierBloodGlucose" sourceName="One Drop" sourceVersion="3.8.0.0" unit="mg/dL" creationDate="2017-05-24 16:07:48 +0200" startDate="2017-05-24 14:33:16 +0200" endDate="2017-05-24 14:33:16 +0200" value="70">
  <MetadataEntry key="App Source" value="OneDrop"/>
  <MetadataEntry key="HKWasUserEntered" value="0"/>
  <MetadataEntry key="HKExternalUUID" value="MquxWsXwnwYjNuuvW93xPmFNkVZ7h7zX"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierBloodGlucose" sourceName="Health" sourceVersion="10.3.1" unit="mg/dL" creationDate="2017-05-25 13:58:55 +0200" startDate="2017-05-25 13:58:00 +0200" endDate="2017-05-25 13:58:00 +0200" value="99">
  <MetadataEntry key="HKWasUserEntered" value="1"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierBloodGlucose" sourceName="mySugr" sourceVersion="1661" unit="mg/dL" creationDate="2017-05-25 14:01:27 +0200" startDate="2017-05-25 13:58:54 +0200" endDate="2017-05-25 13:58:54 +0200" value="111">
  <MetadataEntry key="HKExternalUUID" value="AD185FE9-F7C1-43B9-9DFF-CB5BCA40E1B2"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierBloodGlucose" sourceName="One Drop" sourceVersion="3.8.0.0" unit="mg/dL" creationDate="2017-05-25 14:02:29 +0200" startDate="2017-05-25 13:58:54 +0200" endDate="2017-05-25 13:58:54 +0200" value="111">
  <MetadataEntry key="App Source" value="OneDrop"/>
  <MetadataEntry key="HKWasUserEntered" value="0"/>
  <MetadataEntry key="HKExternalUUID" value="kJj8huH67dMXMUTuE5AyO7PPbsSugEvV"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierBloodGlucose" sourceName="One Drop" sourceVersion="3.8.0.0" unit="mg/dL" creationDate="2017-05-25 14:02:30 +0200" startDate="2017-05-25 13:58:00 +0200" endDate="2017-05-25 13:58:00 +0200" value="99">
  <MetadataEntry key="App Source" value="OneDrop"/>
  <MetadataEntry key="HKWasUserEntered" value="0"/>
  <MetadataEntry key="HKExternalUUID" value="IPwv3mTJInzlJuKWFteXtgfIDuPwQek4"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierBloodGlucose" sourceName="One Drop" sourceVersion="3.8.0.0" unit="mg/dL" creationDate="2017-05-25 14:03:31 +0200" startDate="2017-05-25 14:03:22 +0200" endDate="2017-05-25 14:03:22 +0200" value="161">
  <MetadataEntry key="App Source" value="OneDrop"/>
  <MetadataEntry key="HKWasUserEntered" value="1"/>
  <MetadataEntry key="HKExternalUUID" value="lBCl5bmV15ylSOYa00rtSPuWph9hB0ch"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierBloodGlucose" sourceName="Health" sourceVersion="10.3.1" unit="mg/dL" creationDate="2017-07-05 07:39:49 +0200" startDate="2017-07-05 07:39:00 +0200" endDate="2017-07-05 07:39:00 +0200" value="88">
  <MetadataEntry key="HKWasUserEntered" value="1"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierBloodGlucose" sourceName="One Drop" sourceVersion="3.8.2.2" unit="mg/dL" creationDate="2017-07-05 07:42:03 +0200" startDate="2017-07-05 07:41:58 +0200" endDate="2017-07-05 07:41:58 +0200" value="66">
  <MetadataEntry key="App Source" value="OneDrop"/>
  <MetadataEntry key="HKExternalUUID" value="FZyUfeDqOL5eb2kPeoJJ8XtkhlcP68Vm"/>
  <MetadataEntry key="HKWasUserEntered" value="1"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierBloodGlucose" sourceName="mySugr" sourceVersion="1673" unit="mg/dL" creationDate="2017-07-05 07:43:09 +0200" startDate="2017-07-05 07:43:04 +0200" endDate="2017-07-05 07:43:04 +0200" value="22">
  <MetadataEntry key="HKExternalUUID" value="949165AE-7E39-4E08-BCC8-02F96F93E0DA"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierBloodGlucose" sourceName="iGluco" sourceVersion="39" unit="mg/dL" creationDate="2017-07-05 07:44:52 +0200" startDate="2017-07-05 07:44:00 +0200" endDate="2017-07-05 07:44:00 +0200" value="45">
  <MetadataEntry key="Meal Context" value="Before Breakfast"/>
  <MetadataEntry key="HKAndonDataIdKey" value="4B4D5171-0D51-4A1F-99D1-5EBAA260A2EE14992334404522000000"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierBloodGlucose" sourceName="iGluco" sourceVersion="39" unit="mg/dL" creationDate="2017-07-05 07:45:17 +0200" startDate="2017-07-05 07:45:01 +0200" endDate="2017-07-05 07:45:01 +0200" value="99">
  <MetadataEntry key="Took Insulin" value="Yes"/>
  <MetadataEntry key="Meal Context" value="Before Dinner"/>
  <MetadataEntry key="HKAndonDataIdKey" value="4B4D5171-0D51-4A1F-99D1-5EBAA260A2EE14992335019981000000"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierBloodGlucose" sourceName="ACCU-CHEK" sourceVersion="3" unit="mg/dL" creationDate="2017-07-05 07:46:39 +0200" startDate="2017-07-05 07:46:30 +0200" endDate="2017-07-05 07:46:30 +0200" value="134">
  <MetadataEntry key="Meter Version" value="Unknown"/>
  <MetadataEntry key="Original Units" value="mg/dL"/>
  <MetadataEntry key="Record ID" value="1ef9406e-a591-42aa-abb0-e4a7356d89ae"/>
  <MetadataEntry key="Data Entry" value="Manual"/>
  <MetadataEntry key="App Version" value="2.1.1.3"/>
  <MetadataEntry key="Meter Model" value="Unknown"/>
  <MetadataEntry key="HKWasUserEntered" value="1"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierBloodGlucose" sourceName="Health" sourceVersion="10.3.1" unit="mg/dL" creationDate="2017-07-10 16:56:39 +0200" startDate="2017-07-10 16:56:00 +0200" endDate="2017-07-10 16:56:00 +0200" value="88">
  <MetadataEntry key="HKWasUserEntered" value="1"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierBloodGlucose" sourceName="Health" sourceVersion="10.3.1" unit="mg/dL" creationDate="2017-07-17 13:12:48 +0200" startDate="2017-07-17 13:12:00 +0200" endDate="2017-07-17 13:12:00 +0200" value="88">
  <MetadataEntry key="HKWasUserEntered" value="1"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierBloodGlucose" sourceName="One Drop" sourceVersion="3.8.3.4" unit="mg/dL" creationDate="2017-07-17 15:33:50 +0200" startDate="2017-07-17 15:33:40 +0200" endDate="2017-07-17 15:33:40 +0200" value="122">
  <MetadataEntry key="App Source" value="OneDrop"/>
  <MetadataEntry key="HKExternalUUID" value="opPvORw8uwGSaKh2dWEx9ZaIoaoH80TN"/>
  <MetadataEntry key="HKWasUserEntered" value="1"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierBloodGlucose" sourceName="mySugr" sourceVersion="1714" unit="mg/dL" creationDate="2017-07-17 15:34:33 +0200" startDate="2017-07-17 15:34:25 +0200" endDate="2017-07-17 15:34:25 +0200" value="142">
  <MetadataEntry key="HKExternalUUID" value="74AAF6BE-9B63-44D7-88A0-71FDBCA9C5F9"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierBloodGlucose" sourceName="iGluco" sourceVersion="1" unit="mg/dL" creationDate="2017-07-17 15:38:38 +0200" startDate="2017-07-17 14:37:56 +0200" endDate="2017-07-17 14:37:56 +0200" value="147">
  <MetadataEntry key="Took Insulin" value="Yes"/>
  <MetadataEntry key="Meal Context" value="Fasting"/>
  <MetadataEntry key="HKAndonDataIdKey" value="4B4D5171-0D51-4A1F-99D1-5EBAA260A2EE150029507647 3000000"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierBloodGlucose" sourceName="ACCU-CHEK" sourceVersion="3" unit="mg/dL" creationDate="2017-07-17 15:43:54 +0200" startDate="2017-07-17 15:43:47 +0200" endDate="2017-07-17 15:43:47 +0200" value="88">
  <MetadataEntry key="Meter Version" value="Unknown"/>
  <MetadataEntry key="Original Units" value="mg/dL"/>
  <MetadataEntry key="Record ID" value="39b63cba-2ad3-4f41-a0b5-750090d13b8b"/>
  <MetadataEntry key="Data Entry" value="Manual"/>
  <MetadataEntry key="App Version" value="2.1.1.3"/>
  <MetadataEntry key="Meter Model" value="Unknown"/>
  <MetadataEntry key="HKWasUserEntered" value="1"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierBloodGlucose" sourceName="Health" sourceVersion="10.3.1" unit="mg/dL" creationDate="2017-09-13 10:55:53 +0200" startDate="2017-09-13 10:55:00 +0200" endDate="2017-09-13 10:55:00 +0200" value="66">
  <MetadataEntry key="HKWasUserEntered" value="1"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierBloodGlucose" sourceName="One Drop" sourceVersion="3.9.2.1" unit="mg/dL" creationDate="2017-10-01 12:41:29 +0200" startDate="2017-10-01 12:41:22 +0200" endDate="2017-10-01 12:41:22 +0200" value="166">
  <MetadataEntry key="App Source" value="OneDrop"/>
  <MetadataEntry key="HKExternalUUID" value="YoNtvJZnQE87RoxW9y7C2zYkTP8Z7XMa"/>
  <MetadataEntry key="HKWasUserEntered" value="1"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierBloodGlucose" sourceName="mySugr" sourceVersion="1833" unit="mg/dL" creationDate="2017-10-01 12:47:17 +0200" startDate="2017-10-01 12:47:07 +0200" endDate="2017-10-01 12:47:07 +0200" value="222">
  <MetadataEntry key="HKExternalUUID" value="CAFE9E09-7635-4165-9C45-99BF57BEBD10"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierBloodGlucose" sourceName="Health" sourceVersion="10.3.1" unit="mg/dL" creationDate="2017-10-30 17:14:13 +0200" startDate="2017-10-30 17:14:00 +0200" endDate="2017-10-30 17:14:00 +0200" value="66">
  <MetadataEntry key="HKWasUserEntered" value="1"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierBodyMass" sourceName="Health" sourceVersion="10.2.1" unit="kg" creationDate="2017-03-05 15:32:13 +0200" startDate="2017-03-05 15:32:00 +0200" endDate="2017-03-05 15:32:00 +0200" value="80">
  <MetadataEntry key="HKWasUserEntered" value="1"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierBodyMass" sourceName="Health" sourceVersion="10.2.1" unit="kg" creationDate="2017-03-05 16:49:36 +0200" startDate="2017-03-05 16:49:00 +0200" endDate="2017-03-05 16:49:00 +0200" value="152">
  <MetadataEntry key="HKWasUserEntered" value="1"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierBodyMass" sourceName="Health" sourceVersion="10.2.1" unit="kg" creationDate="2017-03-16 09:58:00 +0200" startDate="2017-03-16 09:57:00 +0200" endDate="2017-03-16 09:57:00 +0200" value="70.3068">
  <MetadataEntry key="HKWasUserEntered" value="1"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierBodyMass" sourceName="MyFitnessPal" sourceVersion="19511" unit="kg" creationDate="2017-04-06 13:25:46 +0200" startDate="2017-04-05 13:25:00 +0200" endDate="2017-04-05 13:25:00 +0200" value="52.0003"/>
 <Record type="HKQuantityTypeIdentifierBodyMass" sourceName="MyFitnessPal" sourceVersion="19511" unit="kg" creationDate="2017-04-16 19:33:31 +0200" startDate="2017-04-06 19:33:00 +0200" endDate="2017-04-06 19:33:00 +0200" value="70.4547"/>
 <Record type="HKQuantityTypeIdentifierBodyMass" sourceName="MyFitnessPal" sourceVersion="19511" unit="kg" creationDate="2017-04-27 16:05:43 +0200" startDate="2017-04-13 16:05:00 +0200" endDate="2017-04-13 16:05:00 +0200" value="51.9998"/>
 <Record type="HKQuantityTypeIdentifierBodyMass" sourceName="MyFitnessPal" sourceVersion="19511" unit="kg" creationDate="2017-04-27 16:06:08 +0200" startDate="2017-04-25 16:06:00 +0200" endDate="2017-04-25 16:06:00 +0200" value="59.9998"/>
 <Record type="HKQuantityTypeIdentifierBodyMass" sourceName="MyFitnessPal" sourceVersion="19928" unit="kg" creationDate="2017-05-14 15:24:45 +0200" startDate="2017-04-27 15:24:00 +0200" endDate="2017-04-27 15:24:00 +0200" value="59.9998"/>
 <Record type="HKQuantityTypeIdentifierBodyMass" sourceName="8fit" sourceVersion="302" unit="kg" creationDate="2017-06-26 07:39:09 +0200" startDate="2017-06-26 07:39:09 +0200" endDate="2017-06-26 07:39:09 +0200" value="79">
  <MetadataEntry key="reportID" value="982eb2de-522e-43ef-b0dc-54bc0ffcb042"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierBodyMass" sourceName="MyFitnessPal" sourceVersion="20355" unit="kg" creationDate="2017-06-26 08:40:02 +0200" startDate="2017-06-21 08:40:00 +0200" endDate="2017-06-21 08:40:00 +0200" value="50.1002"/>
 <Record type="HKQuantityTypeIdentifierBodyMass" sourceName="MyFitnessPal" sourceVersion="20355" unit="kg" creationDate="2017-06-26 08:40:02 +0200" startDate="2017-05-14 08:40:00 +0200" endDate="2017-05-14 08:40:00 +0200" value="50.1002"/>
 <Record type="HKQuantityTypeIdentifierBodyMass" sourceName="Health" sourceVersion="10.3.1" unit="kg" creationDate="2017-07-16 16:58:52 +0200" startDate="2017-07-16 16:58:00 +0200" endDate="2017-07-16 16:58:00 +0200" value="55.7919">
  <MetadataEntry key="HKWasUserEntered" value="1"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierBodyMass" sourceName="Health" sourceVersion="10.3.1" unit="kg" creationDate="2017-07-17 13:19:18 +0200" startDate="2017-07-17 13:19:00 +0200" endDate="2017-07-17 13:19:00 +0200" value="23.1332">
  <MetadataEntry key="HKWasUserEntered" value="1"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierBodyMass" sourceName="MyFitnessPal" sourceVersion="20531" unit="kg" creationDate="2017-07-17 15:04:35 +0200" startDate="2017-06-26 15:04:00 +0200" endDate="2017-06-26 15:04:00 +0200" value="78.9999"/>
 <Record type="HKQuantityTypeIdentifierBodyMass" sourceName="MyFitnessPal" sourceVersion="20531" unit="kg" creationDate="2017-07-17 15:13:36 +0200" startDate="2017-07-16 15:13:00 +0200" endDate="2017-07-16 15:13:00 +0200" value="55.7919"/>
 <Record type="HKQuantityTypeIdentifierBodyMass" sourceName="8fit" sourceVersion="311" unit="kg" creationDate="2017-07-19 10:39:12 +0200" startDate="2017-07-19 10:39:12 +0200" endDate="2017-07-19 10:39:12 +0200" value="66.6">
  <MetadataEntry key="reportID" value="4fd9165f-b1ae-421a-8b27-36d3a97e73d7"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierBodyMass" sourceName="MyFitnessPal" sourceVersion="20613" unit="kg" creationDate="2017-07-21 15:47:52 +0200" startDate="2017-07-17 15:47:00 +0200" endDate="2017-07-17 15:47:00 +0200" value="49.9999"/>
 <Record type="HKQuantityTypeIdentifierBodyMass" sourceName="MyFitnessPal" sourceVersion="20706" unit="kg" creationDate="2017-08-21 13:17:42 +0200" startDate="2017-07-19 13:17:00 +0200" endDate="2017-07-19 13:17:00 +0200" value="66.6001"/>
 <Record type="HKQuantityTypeIdentifierBodyMass" sourceName="Lose It!" sourceVersion="0" unit="kg" creationDate="2017-08-21 13:24:51 +0200" startDate="2017-08-21 13:24:20 +0200" endDate="2017-08-21 13:24:20 +0200" value="66.6">
  <MetadataEntry key="HKExternalUUID" value="CC08219E-042F-A7A4-AEEC-DEB661DB1659"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierBodyMass" sourceName="Lose It!" sourceVersion="0" unit="kg" creationDate="2017-08-22 15:22:51 +0200" startDate="2017-08-22 12:24:38 +0200" endDate="2017-08-22 12:24:38 +0200" value="71.9398">
  <MetadataEntry key="HKExternalUUID" value="4B96A188-F2F4-CFF0-859E-1A77FC524908"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierBodyMass" sourceName="MyFitnessPal" sourceVersion="20900" unit="kg" creationDate="2017-09-24 12:44:37 +0200" startDate="2017-08-21 12:44:00 +0200" endDate="2017-08-21 12:44:00 +0200" value="59.9998"/>
 <Record type="HKQuantityTypeIdentifierBodyMass" sourceName="MyFitnessPal" sourceVersion="20900" unit="kg" creationDate="2017-09-24 12:45:36 +0200" startDate="2017-08-22 12:45:00 +0200" endDate="2017-08-22 12:45:00 +0200" value="71.9398"/>
 <Record type="HKQuantityTypeIdentifierBodyMass" sourceName="8fit" sourceVersion="321" unit="kg" creationDate="2017-09-24 13:58:36 +0200" startDate="2017-09-24 13:58:36 +0200" endDate="2017-09-24 13:58:36 +0200" value="44.4">
  <MetadataEntry key="reportID" value="c9cb8905-6d49-4fe6-9ee1-2d91e8ca4947"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierBodyMass" sourceName="8fit" sourceVersion="321" unit="kg" creationDate="2017-09-24 14:02:28 +0200" startDate="2017-09-24 14:02:28 +0200" endDate="2017-09-24 14:02:28 +0200" value="48.8">
  <MetadataEntry key="reportID" value="c9cb8905-6d49-4fe6-9ee1-2d91e8ca4947"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierBodyMass" sourceName="MyFitnessPal" sourceVersion="20955" unit="kg" creationDate="2017-10-01 10:43:11 +0200" startDate="2017-09-24 10:43:00 +0200" endDate="2017-09-24 10:43:00 +0200" value="88.0001"/>
 <Record type="HKQuantityTypeIdentifierBodyMass" sourceName="MyFitnessPal" sourceVersion="20955" unit="kg" creationDate="2017-10-01 10:45:29 +0200" startDate="2017-09-28 10:45:00 +0200" endDate="2017-09-28 10:45:00 +0200" value="66"/>
 <Record type="HKQuantityTypeIdentifierBodyMass" sourceName="8fit" sourceVersion="330" unit="kg" creationDate="2017-10-03 10:24:26 +0200" startDate="2017-10-03 10:24:26 +0200" endDate="2017-10-03 10:24:26 +0200" value="55.5">
  <MetadataEntry key="reportID" value="c3e6594d-501f-44b1-b10a-519e2ba393c7"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierBodyMass" sourceName="MyFitnessPal" sourceVersion="20962" unit="kg" creationDate="2017-10-03 10:59:42 +0200" startDate="2017-10-01 10:59:00 +0200" endDate="2017-10-01 10:59:00 +0200" value="54.9999"/>
 <Record type="HKQuantityTypeIdentifierBodyMass" sourceName="Lose It!" sourceVersion="4" unit="kg" creationDate="2017-10-08 15:23:05 +0200" startDate="2017-10-03 10:24:26 +0200" endDate="2017-10-03 10:24:26 +0200" value="55.5">
  <MetadataEntry key="HKExternalUUID" value="CFDF3A9A-1C69-4225-6C72-A438F26F0BE1"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierBodyMass" sourceName="Lose It!" sourceVersion="4" unit="kg" creationDate="2017-10-08 15:23:05 +0200" startDate="2017-10-08 14:10:39 +0200" endDate="2017-10-08 14:10:39 +0200" value="70">
  <MetadataEntry key="HKExternalUUID" value="D300E800-04B5-6B26-1541-A9E9CF335604"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierBodyMass" sourceName="Health" sourceVersion="10.3.1" unit="kg" creationDate="2017-10-30 16:50:05 +0200" startDate="2017-10-30 16:50:00 +0200" endDate="2017-10-30 16:50:00 +0200" value="56">
  <MetadataEntry key="HKWasUserEntered" value="1"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierBodyMass" sourceName="Lose It!" sourceVersion="0" unit="kg" creationDate="2017-10-30 16:50:51 +0200" startDate="2017-10-30 16:50:00 +0200" endDate="2017-10-30 16:50:00 +0200" value="56">
  <MetadataEntry key="HKExternalUUID" value="66497E2D-9B65-0EB2-D16B-58AEA24799B2"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierBodyMass" sourceName="Connect" sourceVersion="33" unit="kg" creationDate="2017-10-31 10:25:33 +0200" startDate="2017-09-23 23:00:00 +0200" endDate="2017-09-23 23:00:00 +0200" value="52"/>
 <Record type="HKQuantityTypeIdentifierBodyMass" sourceName="Nutrino" sourceVersion="2.15.0.6" unit="kg" creationDate="2017-10-31 17:07:56 +0200" startDate="2017-10-31 17:07:56 +0200" endDate="2017-10-31 17:07:56 +0200" value="70.0347">
  <MetadataEntry key="HKExternalUUID" value="acu0jkcg#AV9y-YUE8akmkjRi0AFU"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierBodyMass" sourceName="Lose It!" sourceVersion="0" unit="kg" creationDate="2017-10-31 17:09:02 +0200" startDate="2017-10-31 17:07:56 +0200" endDate="2017-10-31 17:07:56 +0200" value="70.0347">
  <MetadataEntry key="HKExternalUUID" value="53C8AA45-6725-BB7D-E94F-DD2D096FB69C"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierBodyMass" sourceName="MyFitnessPal" sourceVersion="21413" unit="kg" creationDate="2017-11-06 11:25:28 +0200" startDate="2017-10-03 10:25:00 +0200" endDate="2017-10-03 10:25:00 +0200" value="56.0001"/>
 <Record type="HKQuantityTypeIdentifierBodyMass" sourceName="MyFitnessPal" sourceVersion="21413" unit="kg" creationDate="2017-11-06 11:26:28 +0200" startDate="2017-10-08 10:26:00 +0200" endDate="2017-10-08 10:26:00 +0200" value="70.0002"/>
 <Record type="HKQuantityTypeIdentifierBodyMass" sourceName="MyFitnessPal" sourceVersion="21413" unit="kg" creationDate="2017-11-06 11:26:28 +0200" startDate="2017-10-23 10:26:00 +0200" endDate="2017-10-23 10:26:00 +0200" value="51.9998"/>
 <Record type="HKQuantityTypeIdentifierBodyMass" sourceName="MyFitnessPal" sourceVersion="21413" unit="kg" creationDate="2017-11-06 11:26:28 +0200" startDate="2017-10-30 11:26:00 +0200" endDate="2017-10-30 11:26:00 +0200" value="56.0001"/>
 <Record type="HKQuantityTypeIdentifierBodyMass" sourceName="MyFitnessPal" sourceVersion="21413" unit="kg" creationDate="2017-11-06 11:26:28 +0200" startDate="2017-10-31 11:26:00 +0200" endDate="2017-10-31 11:26:00 +0200" value="70.0347"/>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Connect" sourceVersion="33" unit="count/min" creationDate="2017-10-31 10:19:51 +0200" startDate="2017-10-09 17:46:00 +0200" endDate="2017-10-09 17:46:00 +0200" value="49"/>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Connect" sourceVersion="33" unit="count/min" creationDate="2017-10-31 10:19:51 +0200" startDate="2017-10-09 17:06:00 +0200" endDate="2017-10-09 17:06:00 +0200" value="90"/>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Connect" sourceVersion="33" unit="count/min" creationDate="2017-10-31 10:19:51 +0200" startDate="2017-10-09 17:04:00 +0200" endDate="2017-10-09 17:04:00 +0200" value="119"/>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Connect" sourceVersion="33" unit="count/min" creationDate="2017-10-31 10:19:51 +0200" startDate="2017-10-09 17:02:00 +0200" endDate="2017-10-09 17:02:00 +0200" value="104"/>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Connect" sourceVersion="33" unit="count/min" creationDate="2017-10-31 10:19:51 +0200" startDate="2017-10-09 17:00:00 +0200" endDate="2017-10-09 17:00:00 +0200" value="95"/>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Connect" sourceVersion="33" unit="count/min" creationDate="2017-10-31 10:19:51 +0200" startDate="2017-10-09 16:58:00 +0200" endDate="2017-10-09 16:58:00 +0200" value="98"/>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Connect" sourceVersion="33" unit="count/min" creationDate="2017-10-31 10:19:51 +0200" startDate="2017-10-09 16:56:00 +0200" endDate="2017-10-09 16:56:00 +0200" value="100"/>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Connect" sourceVersion="33" unit="count/min" creationDate="2017-10-31 10:19:51 +0200" startDate="2017-10-09 16:54:00 +0200" endDate="2017-10-09 16:54:00 +0200" value="125"/>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Connect" sourceVersion="33" unit="count/min" creationDate="2017-10-31 10:19:51 +0200" startDate="2017-10-09 16:52:00 +0200" endDate="2017-10-09 16:52:00 +0200" value="138"/>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Connect" sourceVersion="33" unit="count/min" creationDate="2017-10-31 10:19:51 +0200" startDate="2017-10-09 16:50:00 +0200" endDate="2017-10-09 16:50:00 +0200" value="134"/>